name: BugSigDB Cuation
on:
  issues:
    types: [opened, edited] 

jobs:

  curation-comment:
    permissions:
      issues: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - uses: r-lib/actions/setup-r@v2

      - name: Install stringr
        run: install.packages("stringr", repos = "https://cloud.r-project.org")
        shell: Rscript {0}

      - name: Get DOI
        id: get-doi
        run: |
          comments <- stringr::str_split("${{ github.event.issue.body }}", "\n", simplify = TRUE)
          for (comment in comments) {
            if (stringr::str_detect(comment, "doi:")) {
              doi_comment <- comment
              break
            }  
          }
          doi <- stringr::str_split(doi_comment, ":", simplify = TRUE)[2]

          crossref <- paste("https://api.crossref.org/works", doi, sep = "/")
          crossref_resp <- httr2::request(crossref) |>
            httr2::req_perform() |>
            httr2::resp_body_json(simplifyVector = TRUE)
          
          author <- ""
          if ('author' %in% names(crossref_resp$message)) {
            author <- paste(crossref_resp$message$author$given[1],
                            crossref_resp$message$author$family[1],
                            sep = " ")
          }
          
          eutils <- paste0("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/",
                           "esearch.fcgi?db=pubmed&term=",
                           doi, "[DOI]&retmode=json")
          
          eutils_resp <- httr2::request(eutils) |>
            httr2::req_perform() |>
            httr2::resp_body_json(simplifyVector = TRUE)
          
          pmid <- eutils_resp$esearchresult$idlist
          print(doi)
          print(author)
          print(pmid)
        shell: Rscript {0}
#
#      - run: gh issue comment "$NUMBER" --body "$BODY"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          GH_REPO: ${{ github.repository }}
#          NUMBER: ${{ github.event.issue.number }}
#          BODY: >
#            Lorem ipsum is placeholder text commonly used in the graphic, print,
#            and publishing industries for previewing layouts and visual mockups.
