name: BugSigDB Cuation
on:
  issues:
    types: [opened] 
#  issues_comment:
#    types: [created]

jobs:

  curation-comment:
    permissions:
      issues: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container: bioconductor/bioconductor_docker:devel
    runs-on: ubuntu-latest

    steps:

      - name: Install dependencies
        run: |
         Rscript -e "install.packages(c('stringr', 'httr2'), repos = 'https://cloud.r-project.org', dependencies = c('Depends', 'Imports'))"

      - name: Get DOI
        id: get-doi
        run: |
          doi <- ""
          comments <- stringr::str_split("${{ github.event.issue.body }}", "\n", simplify = TRUE)
          for (comment in comments) {
            if (stringr::str_detect(comment, "[0-9.]+/[A-Za-z0-9.-]+")) {
              doi <- comment
              break
            }  
          }

          crossref <- paste("https://api.crossref.org/works", doi, sep = "/")
          cr <- httr2::request(crossref) |>
            httr2::req_perform() |>
            httr2::resp_body_json(simplifyVector = TRUE)

          title <- ifelse("title" %in% names(cr$message),
            cr$message$title,
            "")

          year <- ifelse("published" %in% names(cr$message),
            cr$message$published$`date-parts`[1],
            "")

          journal <- ifelse("container-title" %in% names(cr$message),
            cr$message$`container-title`[[1]],
            "")

          author <- ""
          if ('author' %in% names(cr$message)) {
            author <- paste(cr$message$author$given[1],
                            cr$message$author$family[1],
                            sep = " ")
          }

          source <- ifelse("resource" %in% names(cr$message),
                           cr$message$resource$primary$URL,
                           "")
          
          eutils <- paste0("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/",
                           "esearch.fcgi?db=pubmed&term=",
                           doi, "[DOI]&retmode=json")
          
          er <- httr2::request(eutils) |>
            httr2::req_perform() |>
            httr2::resp_body_json(simplifyVector = TRUE)
          
          pmid <- er$esearchresult$idlist
          system(paste0("echo DOI=", doi, " >> $GITHUB_OUTPUT"))
          system(paste0("echo AUTHOR=", author, " >> $GITHUB_OUTPUT"))
          system(paste0("echo TITLE=", title, " >> $GITHUB_OUTPUT"))
          system(paste0("echo JOURNAL=", journal, " >> $GITHUB_OUTPUT"))
          system(paste0("echo YEAR=", year, " >> $GITHUB_OUTPUT"))
          system(paste0("echo PMID=", pmid, " >> $GITHUB_OUTPUT"))
          print(paste("DOI:", doi))
          print(paste("PMID:", PMID))
          print(paste("TITLE:", TITLE))
          print(paste("AUTHOR:", AUTHOR))
          print(paste("JOURNAL:", JOURNAL))
          print(paste("YEAR:", YEAR))
        shell: Rscript {0}

      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "${{ steps.get-doi.outputs.TITLE }}"
            })
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 
              `
              ### Study
              ${{ steps.get-doi.outputs.TITLE }}

              ### DOI
              ${{ steps.get-doi.outputs.DOI }}

              ### PMID
              ${{ steps.get-doi.outputs.PMID}}

              ### Author
              ${{ steps.get-doi.outputs.AUTHOR }}

              ### Journal
              ${{ steps.get-doi.outputs.JOURNAL}}

              ### Year
              ${{ steps.get-doi.outputs.YEAR }}

              👋 Thanks for submitting!`
            })
